version: '3.8'

services:
  web:
    image: dockerasp:latest
    ports:
      - "8080:80"
    depends_on:
      - redis
    environment:
      - REDIS_CONNECTION=redis:6379

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
